import type { Metadata } from "next";
import "./scss/custom.scss";
import { Container } from "react-bootstrap";
import { MyNavbar } from "./_lib/components/MyNavbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Container>
                    <MyNavbar></MyNavbar>
                    {children}
                </Container>
            </body>
        </html>
    );
}
